language: python
cache: pip
notifications:
  slack: dealien-dev:vtzdndxTlMJtUsVtFS6yfjVN
python:
  - "3.6"
install:
  - pip install pipreqs
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codacy-coverage
  - pip install codecov
script:
  - python main.py --test-run
  - coverage run main.py --test-run
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
